default:
  tags: [cpu]

variables:
  GIT_SUBMODULE_STRATEGY: recursive # PTO-ISA is a submodule

stages:
   - test
   - bench

# Define the workflow rules manually to make sure only a single pipeline
# is created for each MR update. Without that, GitLab creates one pipeline
# for branch update and one for MR update.
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_DRAFT'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

##################################################
# On-device accuracy tests (one job per test)    #
##################################################
.accuracy_test_x86_910B4:
  image: quay.io/ascend/cann:9.1.0-910b-ubuntu22.04-py3.12
  stage: test
  tags:
    - docker_npu # Run accuracy tests on-device NPU (x86-64 / 910B4)
  before_script:
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh
    - pip3 install pyyaml setuptools packaging
    - pip3 install torch==2.9.0 --index-url https://download.pytorch.org/whl/cpu
    - pip3 install torch-npu==2.9.0
    - pip3 install -e .

# accuracy tests (GDN)
test_gdn_single_kernels:
  extends: .accuracy_test_x86_910B4
  script:
    - python3 tests/test_gdn_single_kernels.py --H-list 16,32

test_gdn_e2e:
  extends: .accuracy_test_x86_910B4
  script:
    - python3 tests/test_gdn_e2e.py --no-triton

# accuracy tests (KDA)
test_kda_single_kernels:
  extends: .accuracy_test_x86_910B4
  script:
    - python3 tests/test_kda_single_kernels.py

test_kda_e2e:
  extends: .accuracy_test_x86_910B4
  script:
    - python3 tests/test_kda_e2e.py

bench_gdn_kernels:
  image: quay.io/ascend/vllm-ascend:v0.23.0rc1
  stage: bench
  tags:
    - docker_npu_910B2 # Build and test on-device (aarch64 / 910B2)
  before_script:
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh
  script:
    - python benchmarks/kernel/bench_gdn_kernels.py --device npu:0 --n-seq 16 --l-seg 8192 --H-list 16
  when: manual
  allow_failure: true


bench_lm_eval_qwen35_0_8b:
  image: quay.io/ascend/vllm-ascend:v0.23.0rc1
  stage: bench
  tags:
    - docker_npu_910B2 # Build and test on-device (aarch64 / 910B2)
  before_script:
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh
  script:
    - pip install -U lm-eval
    - mkdir -p outputs/data/eval/
    - python benchmarks/eval_acc/run_lm_eval.py --preset qwen35_0_8b --output-json outputs/data/eval/qwen35_0_8b_pto.json
  when: manual
  allow_failure: true
  artifacts:
    expire_in: 1 day
    paths:
      - outputs/data/
