repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: check-toml
    - id: detect-private-key
    - id: check-ast
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
    - id: clang-format
      types_or: [c++, c]
